language: php
php: 7.4
dist: xenial

notifications:
  email:
    recipients:
      - lr@amp.co
    on_success: change
    on_failure: always
    on_error: always

env:
  - TEST_GROUP=latest
  - TEST_GROUP=two_three

install:
  - cd test
  - composer install --no-interaction
  - composer require ampersand/travis-vanilla-magento dev-$TRAVIS_BRANCH || composer require ampersand/travis-vanilla-magento $TRAVIS_BRANCH

script:
  - if [[ $TEST_GROUP = two_three ]]; then  phpenv versions; phpenv global 7.2; fi
  - if [[ $TEST_GROUP = two_three ]]; then  NAME=$TEST_GROUP WITH_SAMPLE_DATA=1 VERSION=2.3.3  . ./vendor/bin/travis-install-magento.sh; fi
  - if [[ $TEST_GROUP = latest ]]; then  
        sudo apt-get remove elasticsearch -y &&\
        curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb &&\
        sudo dpkg -i --force-confnew elasticsearch-7.6.2-amd64.deb &&\
        sudo chown elasticsearch:elasticsearch /etc/default/elasticsearch &&\
        sudo service elasticsearch restart &&\
        sleep 5 &&\
        curl -XGET 'localhost:9200';
    fi
  - if [[ $TEST_GROUP = latest ]];    then  NAME=$TEST_GROUP WITH_SAMPLE_DATA=1                . ./vendor/bin/travis-install-magento.sh; fi
  - echo "Travis Run Done"

addons:
  apt:
    packages:
    - postfix
    - apache2
    - libapache2-mod-fastcgi

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
