language: php
php: 7.3

notifications:
  email:
    recipients:
      - lr@amp.co
    on_success: change
    on_failure: always
    on_error: always

env:
  - TEST_GROUP=latest
  - TEST_GROUP=two_three

install:
  - cd test
  - composer install --no-interaction
  - composer require ampersand/travis-vanilla-magento dev-$TRAVIS_BRANCH

script:
  - if [[ $TEST_GROUP = two_three ]]; then  NAME=$TEST_GROUP WITH_SAMPLE_DATA=1 VERSION=2.3.3  ./vendor/bin/travis-install-magento.sh; fi
  - if [[ $TEST_GROUP = latest ]];    then  NAME=$TEST_GROUP WITH_SAMPLE_DATA=1                ./vendor/bin/travis-install-magento.sh; fi

addons:
  apt:
    packages:
    - postfix
    - apache2
    - libapache2-mod-fastcgi

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
